import { Manrope } from 'next/font/google'
import "./globals.css";

const manrope = Manrope({
  subsets: ['latin', 'cyrillic'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang='ru' className={manrope.className}>
        <body>{children}</body>
      </html>
  ); 
}
