import { Manrope } from 'next/font/google'
import "./globals.css";

import Header from '@/ui/header/header';
import Footer from '@/ui/footer/footer';
const manrope = Manrope({
  subsets: ['latin', 'cyrillic'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang='ru' className={manrope.className}>
        <body className='p-4'>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
  ); 
}
