import { Manrope } from 'next/font/google'
import "./globals.css";

const manroperu = Manrope({
  subsets: ['cyrillic'],
})

const manropelat = Manrope({
  subsets: ['latin'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  let htmlContent;

  if (lang === 'ru') {
    htmlContent = (
      <html lang="ru" className={manroperu.className}>
        <body>{children}</body>
      </html>
    );
  } else if (lang === 'en') {
    htmlContent = (
      <html lang="en" className={manropelat.className}>
        <body>{children}</body>
      </html>
    );
  } else {
    htmlContent = (
      <html lang="en">
        <body>{children}</body>
      </html>
    );
  }

  return htmlContent;
}
